[colors.bright]
black = "0x808080"
blue = "0x0066FF"
cyan = "0x00FFFF"
green = "0x33FF00"
magenta = "0xCC00FF"
red = "0xFE0100"
white = "0xFFFFFF"
yellow = "0xFEFF00"

[colors.cursor]
cursor = "0xffffff"
text = "0xF81CE5"

[colors.normal]
black = "0x000000"
blue = "0x0066FF"
cyan = "0x00FFFF"
green = "0x33FF00"
magenta = "0xCC00FF"
red = "0xFE0100"
white = "0xD0D0D0"
yellow = "0xFEFF00"

[colors.primary]
background = "0x101010"
foreground = "0xffffff"

[font]
size = 14

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "Copy"
mods = "Shift"
mouse = "Left"

[[mouse.bindings]]
action = "Paste"
mods = "Shift"
mouse = "Right"

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 500

[keyboard]
bindings = [
{ key = "T", mods = "Command", action = "CreateNewTab" },
{ key = "N", mods = "Command", action = "SpawnNewInstance" },
{ key = "W", mods = "Command", action = "Quit" },
{ key = "Tab", mods = "Control", action = "SelectNextTab" },
{ key = "Tab", mods = "Control | Shift", action = "SelectPreviousTab" },
{ key = "Left", mods = "Command", chars = "\u0001" },
{ key = "Right", mods = "Command", chars = "\u0005" },
{ key = "Home", chars = "\u0001" },
{ key = "End", chars = "\u0005" },
{ key = "V", mods = "Command | Shift", action = "ToggleViMode" },
{ key = "Minus", mods = "Control", action = "DecreaseFontSize" },
{ key = "Equals", mods = "Control", action = "IncreaseFontSize" },
{ key = "Plus", mods = "Control | Shift", action = "IncreaseFontSize" },
{ key = "Key0", mods = "Control", action = "ResetFontSize" },
]

[bell]
animation = "EaseoutExpo"
duration = 0
command = { program = "sh", args = ["-c", "printf '\\a'"] }

[window]
opacity = 0.9
option_as_alt = "Both"
dynamic_padding = true
decorations = "Full"

[window.padding]
x = 20
y = 20

[scrolling]
history = 100000
